ignore:
  - "watchdog/watchdog.go"
  - "storage/store/sql/specific_postgres.go" # Can't test for postgres

coverage:
  status:
    patch: off
    project:
      default:
        target: 75%
        threshold: null

