package remote

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/TwiN/gatus/v5/client"
	"github.com/TwiN/logr"
)

const KeyPrefix = "@remote:"

// NOTICE: This is an experimental alpha feature and may be updated/removed in future versions.
// For more information, see https://github.com/TwiN/gatus/issues/64

type Config struct {
	// Instances is a list of remote instances to retrieve endpoint statuses from.
	Instances []Instance `yaml:"instances,omitempty"`

	// ClientConfig is the configuration of the client used to communicate with the provider's target
	ClientConfig *client.Config `yaml:"client,omitempty"`
}

type Instance struct {
	EndpointPrefix string `yaml:"endpoint-prefix"`
	URL            string `yaml:"url"`

	// Authorization is sent as the Authorization header when retrieving data from the remote instance.
	// Use this when the remote Gatus API is protected (basic auth, bearer token, etc.).
	Authorization string `yaml:"authorization,omitempty"`
}

// PrefixedKey returns a key that identifies an endpoint as belonging to a remote instance.
func PrefixedKey(instanceIndex int, originalKey string) string {
	return fmt.Sprintf("%s%d:%s", KeyPrefix, instanceIndex, originalKey)
}

// IsPrefixedKey reports whether key was generated by PrefixedKey.
func IsPrefixedKey(key string) bool {
	_, _, ok := ParsePrefixedKey(key)
	return ok
}

// ParsePrefixedKey splits a remote endpoint key into its instance index and original key.
func ParsePrefixedKey(key string) (instanceIndex int, originalKey string, ok bool) {
	if !strings.HasPrefix(key, KeyPrefix) {
		return 0, "", false
	}
	rest := strings.TrimPrefix(key, KeyPrefix)
	colonIndex := strings.Index(rest, ":")
	if colonIndex <= 0 {
		return 0, "", false
	}
	parsedIndex, err := strconv.Atoi(rest[:colonIndex])
	if err != nil || parsedIndex < 0 {
		return 0, "", false
	}
	parsedKey := rest[colonIndex+1:]
	if len(parsedKey) == 0 {
		return 0, "", false
	}
	return parsedIndex, parsedKey, true
}

// EndpointBaseURL returns the base URL for individual endpoint resources on a remote instance.
// For example, https://status.example.org/api/v1/endpoints/statuses becomes
// https://status.example.org/api/v1/endpoints.
func (i Instance) EndpointBaseURL() string {
	baseURL := strings.TrimSuffix(strings.TrimSpace(i.URL), "/")
	if strings.HasSuffix(baseURL, "/statuses") {
		baseURL = strings.TrimSuffix(baseURL, "/statuses")
	}
	return baseURL
}

// BuildEndpointURL builds a remote endpoint resource URL.
// subPath must start with "/" (e.g. "/statuses", "/health/badge.svg").
func (i Instance) BuildEndpointURL(endpointKey, subPath string) string {
	return i.EndpointBaseURL() + "/" + url.PathEscape(endpointKey) + subPath
}

func (i Instance) ApplyRequestHeaders(request *http.Request, forwardHeaders http.Header) {
	if forwardHeaders != nil {
		if cookie := forwardHeaders.Get("Cookie"); len(cookie) > 0 {
			request.Header.Set("Cookie", cookie)
		}
		if authorization := forwardHeaders.Get("Authorization"); len(authorization) > 0 {
			request.Header.Set("Authorization", authorization)
		}
	}
	if len(i.Authorization) > 0 {
		request.Header.Set("Authorization", i.Authorization)
	}
}

func (c *Config) ValidateAndSetDefaults() error {
	if c.ClientConfig == nil {
		c.ClientConfig = client.GetDefaultConfig()
	} else {
		if err := c.ClientConfig.ValidateAndSetDefaults(); err != nil {
			return err
		}
	}
	if len(c.Instances) > 0 {
		logr.Warn("WARNING: Your configuration is using 'remote', which is in alpha and may be updated/removed in future versions.")
		logr.Warn("WARNING: See https://github.com/TwiN/gatus/issues/64 for more information")
	}
	return nil
}
