{
 "title": "Gatus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total results per minute",
   "type": "graph",
   "description": "Number of results per minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total[5m])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Successful results per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[5m])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Unsuccessful results",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(gatus_results_total{success=\"false\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Unsuccessful results per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"false\"}[5m])*60) by (key)",
     "legendFormat": "{{key}} "
    }
   ]
  }
 ]
}