name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.examples/**'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.examples/**'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.26.3
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build binary to make sure it works
        run: go build
      - name: Test
        # We're using "sudo" because one of the tests leverages ping, which requires super-user privileges.
        # As for the 'env "PATH=$PATH" "GOROOT=$GOROOT"', we need it to use the same "go" executable that
        # was configured by the "Set up Go" step (otherwise, it'd use sudo's "go" executable)
        run: sudo env "PATH=$PATH" "GOROOT=$GOROOT" go test ./... -race
